import type { Idea, Script, EditorBrief } from './types';

export const mockIdeas: Idea[] = [
  {
    id: '1',
    userId: '1',
    channelId: 'innov8ai',
    title: 'Cursor AI Agent Mode — The Feature Nobody Talks About',
    description: 'Deep dive into Cursor\'s new agent mode that writes, debugs, and deploys code autonomously.',
    angle: 'First-mover angle — most creators covered basic Cursor, nobody focused on agent mode',
    hooks: [
      'Cursor just made every other code editor obsolete',
      'I replaced my entire dev workflow with one button',
      'This AI feature is going to kill junior dev jobs',
    ],
    format: 'reel',
    tags: ['tool-review', 'AI', 'coding'],
    status: 'developed',
    priority: 9,
    viralityScore: 94,
    targetAudience: 'Developers and tech enthusiasts interested in AI coding tools',
    keyPoints: [
      'Agent mode vs regular Copilot',
      'Live demo: building a full app',
      'Cost comparison with hiring',
      'Limitations and when it fails',
    ],
    ctaStrategy: 'Comment CURSOR for my complete setup guide',
    references: [{ url: 'https://cursor.com', note: 'Official site' }],
    source: 'scout',
    createdAt: '2026-02-23T06:00:00Z',
    updatedAt: '2026-02-23T07:00:00Z',
  },
  {
    id: '2',
    userId: '1',
    channelId: 'alextom',
    title: 'Lovable.dev: From $0 to $4M ARR — The Founder Story',
    description: 'Breaking down how Lovable.dev reached $4M ARR with AI-first approach.',
    angle: 'Founder journey angle — "what can we learn" narrative',
    hooks: [
      'This founder made $4M/year with a tool that writes code for you',
      'The laziest way to build a $4M startup',
    ],
    format: 'reel',
    tags: ['founder-story', 'startup', 'AI'],
    status: 'raw',
    priority: 7,
    viralityScore: 72,
    targetAudience: 'Aspiring founders and indie hackers',
    keyPoints: ['Origin story', 'Growth strategy', 'Tech stack', 'Revenue breakdown'],
    ctaStrategy: 'Follow for more founder breakdowns',
    references: [],
    source: 'scout',
    createdAt: '2026-02-23T06:00:00Z',
    updatedAt: '2026-02-23T06:00:00Z',
  },
  {
    id: '3',
    userId: '1',
    channelId: 'academy',
    title: 'Top 5 AI Avatar Tools Comparison 2026',
    description: 'Comparing the best AI avatar tools for content creators — HeyGen, Synthesia, D-ID, Elai, Colossyan.',
    angle: 'Tutorial comparison — show each tool with same script, let audience decide',
    hooks: [
      'ഈ 5 AI tools ഉപയോഗിച്ച് നിങ്ങൾക്ക് face കാണിക്കാതെ content ഉണ്ടാക്കാം',
    ],
    format: 'reel',
    tags: ['tutorial', 'AI-avatar', 'comparison'],
    status: 'raw',
    priority: 8,
    viralityScore: 78,
    targetAudience: 'Malayalam-speaking creators interested in AI avatars',
    keyPoints: ['Price comparison', 'Quality comparison', 'Ease of use', 'Best for beginners'],
    ctaStrategy: 'Comment AVATAR for free comparison chart',
    references: [],
    source: 'manual',
    createdAt: '2026-02-23T05:00:00Z',
    updatedAt: '2026-02-23T05:00:00Z',
  },
  {
    id: '4',
    userId: '1',
    channelId: 'innov8ai',
    title: 'Claude Code vs Cursor: Which AI Coding Tool Wins?',
    description: 'Head-to-head comparison of Claude Code CLI and Cursor IDE for real development tasks.',
    angle: 'Practical comparison with same project built in both',
    hooks: [
      'I built the same app with Claude Code and Cursor — one was 3x faster',
    ],
    format: 'reel',
    tags: ['comparison', 'AI', 'coding'],
    status: 'scripted',
    priority: 8,
    viralityScore: 85,
    targetAudience: 'Developers choosing between AI coding tools',
    keyPoints: ['Speed test', 'Code quality', 'Cost', 'Best use cases for each'],
    ctaStrategy: 'Comment COMPARE for detailed breakdown PDF',
    references: [],
    source: 'scout',
    createdAt: '2026-02-22T10:00:00Z',
    updatedAt: '2026-02-23T04:00:00Z',
  },
];

export const mockScripts: Script[] = [
  {
    id: '1',
    ideaId: '4',
    userId: '1',
    channelId: 'innov8ai',
    title: 'Claude Code vs Cursor: Which AI Coding Tool Wins?',
    hook: 'I built the same app with Claude Code and Cursor — one was 3x faster, and it\'s not the one you think.',
    hookVariations: [
      'I built the same app with Claude Code and Cursor — one was 3x faster',
      'Stop using Cursor. Here\'s what I switched to.',
      'The AI coding war just got a clear winner.',
    ],
    body: `Here's what happened when I built a full-stack app with both tools.

First, Cursor. I opened the IDE, typed my prompt, and it started generating. The inline suggestions were smooth, the tab completion was fast. Total time: 45 minutes for a working CRUD app.

Then Claude Code. No IDE — just the terminal. I described what I wanted in plain English. It asked clarifying questions, planned the architecture, then built the entire thing. Files, tests, deployment config. Total time: 15 minutes.

But here's the thing most people miss — it's not about speed alone. Claude Code understood the WHY behind my code. It made architectural decisions Cursor wouldn't think about. Error handling, edge cases, proper TypeScript types.

The real difference? Cursor is autocomplete on steroids. Claude Code is a senior developer in your terminal.`,
    cta: 'Comment COMPARE and I\'ll send you my detailed breakdown with exact prompts I used for both tools.',
    outro: 'Follow @innov8.ai for more AI tool comparisons every week.',
    fullScript: '',
    visualCues: [
      { timestamp: '0:00-0:03', visual: 'Split screen — Cursor left, Terminal right', textOverlay: 'Claude Code vs Cursor' },
      { timestamp: '0:03-0:15', visual: 'Screen recording of Cursor generating code', textOverlay: '45 minutes' },
      { timestamp: '0:15-0:30', visual: 'Screen recording of Claude Code in terminal', textOverlay: '15 minutes' },
      { timestamp: '0:30-0:45', visual: 'Side-by-side code quality comparison', textOverlay: 'But speed isn\'t everything...' },
      { timestamp: '0:45-0:55', visual: 'Face cam with results', textOverlay: 'The verdict' },
    ],
    speakerNotes: 'Energy high on hook, slow down on the "here\'s the thing" moment, confident on verdict',
    wordCount: 234,
    estimatedDuration: 58,
    template: 'comparison',
    style: 'educational',
    language: 'en',
    status: 'review',
    version: 2,
    criticScore: { hook: 9, voice: 8, value: 9, cta: 7, overall: 8.4 },
    criticFeedback: 'Strong hook, good pacing. CTA could be more specific about what the breakdown includes. Consider adding a price comparison point.',
    createdAt: '2026-02-23T04:00:00Z',
    updatedAt: '2026-02-23T07:00:00Z',
  },
];

export const mockBriefs: EditorBrief[] = [
  {
    id: '1',
    scriptId: '1',
    userId: '1',
    channelId: 'innov8ai',
    scenes: [
      {
        sceneNum: 1,
        narration: 'I built the same app with Claude Code and Cursor — one was 3x faster',
        visual: 'Dynamic split screen reveal — Cursor logo left, Claude logo right',
        textOverlay: 'CLAUDE CODE vs CURSOR',
        broll: 'Search: "split screen code editor comparison", "AI coding tool"',
        transition: 'Hard cut with glitch effect',
        duration: 3,
      },
      {
        sceneNum: 2,
        narration: 'First, Cursor. Inline suggestions, tab completion, 45 minutes.',
        visual: 'Screen recording of Cursor IDE with code generating in real-time',
        textOverlay: 'Cursor IDE — 45 min ⏱️',
        broll: 'Cursor screen recording (record fresh for this)',
        transition: 'Swipe left',
        duration: 12,
      },
      {
        sceneNum: 3,
        narration: 'Then Claude Code. Terminal only. 15 minutes for everything.',
        visual: 'Screen recording of terminal with Claude Code running',
        textOverlay: 'Claude Code — 15 min ⏱️',
        broll: 'Terminal recording with Claude Code (record fresh)',
        transition: 'Swipe left',
        duration: 15,
      },
      {
        sceneNum: 4,
        narration: 'The real difference — Cursor is autocomplete, Claude Code is a senior dev.',
        visual: 'Side-by-side code comparison, highlighting architecture differences',
        textOverlay: 'Autocomplete vs Senior Dev',
        broll: 'Search: "code architecture diagram", "clean code"',
        transition: 'Zoom in',
        duration: 15,
      },
      {
        sceneNum: 5,
        narration: 'Comment COMPARE for the full breakdown.',
        visual: 'Face cam with both logos, pointing at comment section',
        textOverlay: 'Comment COMPARE 👇',
        broll: 'None — direct to camera',
        transition: 'Fade out',
        duration: 10,
      },
    ],
    musicMood: 'Tech/electronic, medium energy, building tension',
    musicSuggestions: ['Epidemic Sound — "Digital Frontier"', 'Artlist — "Code Runner"'],
    thumbnailConcepts: [
      { concept: 'Split face — Alex looking at both tools', text: 'CURSOR vs CLAUDE CODE', style: 'High contrast, blue vs purple' },
      { concept: 'Terminal with "3x FASTER" in big text', text: '3X FASTER 🚀', style: 'Dark background, green terminal text' },
      { concept: 'Boxing match poster style', text: 'THE AI CODE WAR', style: 'Red and blue corners, dramatic' },
    ],
    caption: '🔥 I built the SAME app with Claude Code and Cursor.\n\nOne took 45 minutes.\nThe other? 15 minutes.\n\nBut speed isn\'t the whole story...\n\nThe REAL winner surprised me. Watch to find out 👆\n\nComment COMPARE for my full breakdown with exact prompts! 📋',
    hashtags: ['#AI', '#CursorAI', '#ClaudeCode', '#CodingTools', '#AIcoding', '#Developer', '#Tech', '#innov8'],
    referenceVideos: [
      { url: 'https://youtube.com/example1', note: 'Similar comparison format — good pacing' },
    ],
    editorNotes: 'Keep transitions snappy. Use code-style font for all text overlays. Add subtle typing sound effects during screen recordings.',
    status: 'draft',
    createdAt: '2026-02-23T07:30:00Z',
  },
];

export const channelMap: Record<string, { name: string; handle: string; color: string }> = {
  innov8ai: { name: 'Innov8 AI', handle: '@innov8.ai', color: '#3B82F6' },
  alextom: { name: 'Alex Tom AI', handle: '@alextom.ai', color: '#8B5CF6' },
  academy: { name: 'Innov8 Academy', handle: '@innov8.academy', color: '#10B981' },
};
